'use client';

import Link from 'next/link';
import AppLayout from '@/components/layout/AppLayout';
import { FileText, CheckCircle2 } from 'lucide-react';

export default function TermsPage() {
  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-xs font-semibold text-[#8A867D] mb-6">
          <Link href="/" className="hover:text-[#101010]">Home</Link>
          <span>/</span>
          <span className="text-[#101010] font-bold">Terms of Service</span>
        </div>

        {/* Header */}
        <div className="mb-10 pb-8 border-b border-[#E8E4DA]">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white border border-[#E8E4DA] text-xs font-black uppercase tracking-wider text-[#101010] mb-3 shadow-xs">
            <FileText className="w-3.5 h-3.5 text-[#D8F651]" />
            <span>TERMS & LICENSING</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-black text-[#101010] tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm sm:text-base text-[#8A867D] mt-3 font-medium">
            Effective Date: March 2026. The legal agreement governing your use of AICORN.
          </p>
        </div>

        {/* Content */}
        <div className="prose prose-lg max-w-none text-[#1A1A1A] space-y-8 text-sm sm:text-base leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">1. Acceptance of Terms</h2>
            <p className="text-[#1A1A1A]/85">
              By accessing, browsing, copying prompts, or submitting content to AICORN, you agree to comply with and be bound by these Terms of Service. If you disagree with any part of these terms, you may not access or use our platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">2. Commercial Use & Prompt License</h2>
            <p className="text-[#1A1A1A]/85">
              AICORN grants you a worldwide, royalty-free, non-exclusive license to copy, adapt, and use prompts cataloged on this platform in your generative AI workflows (including Midjourney, Flux, Veo 3, Kling, Sora, and Claude Code) for both personal and commercial projects.
            </p>
            <div className="p-4 rounded-2xl bg-[#F7F4EE] border border-[#E8E4DA] flex items-start gap-3">
              <CheckCircle2 className="w-5 h-5 text-[#101010] shrink-0 mt-0.5" />
              <div className="text-xs sm:text-sm text-[#101010]">
                <strong>Commercial Clearance:</strong> Output generated by you using prompts discovered on AICORN belongs to you, subject to the terms of the underlying AI model providers.
              </div>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">3. Prohibited Conduct & Zero AI Slop Standard</h2>
            <p className="text-[#1A1A1A]/85">
              To preserve the high quality of AICORN, users agree not to:
            </p>
            <ul className="space-y-2 pl-4">
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span>Submit generic, broken, or low-effort prompts (&quot;AI slop&quot;) designed to pollute discovery.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span>Scrape platform data systematically using unauthorized bots or spiders.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span>Attempt to bypass Supabase database Row Level Security policies or Clerk authentication tokens.</span>
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">4. Disclaimer & Limitations</h2>
            <p className="text-[#1A1A1A]/85">
              Prompts and AI models are provided &quot;as-is&quot;. While AICORN curates and tests all prompts for top aesthetic fidelity, generative AI model outputs inherently vary by seed, model version, and parameter configurations.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">5. Questions & Legal Inquiries</h2>
            <p className="text-[#1A1A1A]/85">
              For legal inquiries regarding terms and intellectual property, please reach out to{' '}
              <a href="mailto:legal@aicorn.design" className="font-bold underline text-[#101010] hover:text-[#FF4B26]">
                legal@aicorn.design
              </a>.
            </p>
          </section>
        </div>

      </div>
    </AppLayout>
  );
}
