import Link from 'next/link';
import AppLayout from '@/components/layout/AppLayout';
import { FileText, CheckCircle2, AlertOctagon, Scale, ShieldAlert, Cpu } from 'lucide-react';

export default function TermsPage() {
  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        
        {/* Breadcrumb */}
        <div className="flex items-center gap-2 text-xs font-semibold text-[#8A867D] mb-6">
          <Link href="/" className="hover:text-[#101010]">Home</Link>
          <span>/</span>
          <span className="text-[#101010] font-bold">Terms of Service</span>
        </div>

        {/* Header */}
        <div className="mb-10 pb-8 border-b border-[#E8E4DA]">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white border border-[#E8E4DA] text-xs font-black uppercase tracking-wider text-[#101010] mb-3 shadow-xs">
            <FileText className="w-3.5 h-3.5 text-[#101010]" />
            <span>TERMS & LICENSING</span>
          </div>
          <h1 className="text-3xl sm:text-5xl font-black text-[#101010] tracking-tight">
            Terms of Service
          </h1>
          <p className="text-sm sm:text-base text-[#8A867D] mt-3 font-medium">
            Effective Date: March 2026. The legal agreement governing your use of AICORN, founded by Pawan Suda.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-10 text-sm sm:text-base leading-relaxed text-[#1A1A1A]">
          
          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">1. Acceptance of Terms</h2>
            <p className="text-[#1A1A1A]/85">
              By accessing, browsing, copying prompts, or submitting content to <strong>AICORN</strong> (https://aicorn-ai.vercel.app/), you agree to comply with and be bound by these Terms of Service. If you disagree with any part of these terms, you may not access or use our platform.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h2 className="text-xl sm:text-2xl font-black text-[#101010]">2. Commercial Use & Prompt License</h2>
            <p className="text-[#1A1A1A]/85">
              AICORN grants you a worldwide, royalty-free, non-exclusive license to copy, adapt, and execute prompts cataloged on this platform in your generative AI workflows (including Midjourney, ChatGPT, Kling AI, Google DeepMind Veo 3, and Runway) for both personal and commercial projects.
            </p>
            <div className="p-4 rounded-2xl bg-white border border-[#E8E4DA] flex items-start gap-3 shadow-xs">
              <CheckCircle2 className="w-5 h-5 text-[#101010] shrink-0 mt-0.5" />
              <div className="text-xs sm:text-sm text-[#101010]">
                <strong>Commercial Clearance:</strong> Output generated by you using prompts discovered on AICORN belongs to you, subject to the terms of the underlying AI model providers. AICORN levies zero royalties or licensing fees on your creative outputs.
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-[#101010] font-black text-xl sm:text-2xl">
              <ShieldAlert className="w-5 h-5 text-[#FF4B26]" />
              <h2>3. Copyrighted Images & DMCA Takedown Procedure</h2>
            </div>
            <p className="text-[#1A1A1A]/85">
              Creators submitting prompts and sample previews to AICORN must hold the necessary rights, licenses, or synthetic generations to share such materials. You may not upload media that infringes upon third-party copyrights, registered trademarks, or likeness rights.
            </p>
            <div className="p-4 rounded-xl bg-[#F7F4EE] border border-[#E8E4DA] space-y-2 text-xs sm:text-sm">
              <p><strong>DMCA & Copyright Inquiries:</strong> If you believe content cataloged on AICORN infringes your copyright or trademark, send an official takedown notice to our designated agent at <a href="mailto:curators@aicorn.design" className="font-bold underline text-[#FF4B26]">curators@aicorn.design</a>.</p>
              <p>Include the URL of the contested prompt, proof of copyright ownership, and a declaration of good faith belief. We review and remove verified infringing content within 48 hours.</p>
            </div>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-[#101010] font-black text-xl sm:text-2xl">
              <AlertOctagon className="w-5 h-5 text-[#FF4B26]" />
              <h2>4. Prohibition of Fake Reviews & Unsupported Claims</h2>
            </div>
            <p className="text-[#1A1A1A]/85">
              AICORN is committed to uncompromising authenticity. To protect users from deceptive marketing:
            </p>
            <ul className="space-y-2 pl-4 text-xs sm:text-sm">
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span><strong>No Fake Metrics or Reviews:</strong> Generating synthetic upvotes, fake testimonials, or automated ratings is strictly prohibited.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span><strong>No Unsupported Model Claims:</strong> Users must specify real, tested AI model parameters (e.g. valid camera angles, aspect ratios, seeds) rather than asserting fictional rendering capabilities.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-[#101010] mt-2 shrink-0"></span>
                <span><strong>Zero AI Slop Policy:</strong> Submissions consisting of low-effort, broken, or hallucinated prompts will be rejected or purged by curators.</span>
              </li>
            </ul>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-[#101010] font-black text-xl sm:text-2xl">
              <Cpu className="w-5 h-5 text-[#101010]" />
              <h2>5. Third-Party AI Models & Embeds</h2>
            </div>
            <p className="text-[#1A1A1A]/85 text-xs sm:text-sm">
              Trademarks including Midjourney, ChatGPT / OpenAI, Kling AI, Google DeepMind Veo 3, and Runway Gen-3 are properties of their respective owners. AICORN is an independent curation directory and is not officially affiliated with or endorsed by these third-party companies. Output behavior varies across model revisions, seeds, and updates.
            </p>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <div className="flex items-center gap-2 text-[#101010] font-black text-xl sm:text-2xl">
              <Scale className="w-5 h-5 text-[#101010]" />
              <h2>6. Governing Law & Contact</h2>
            </div>
            <p className="text-[#1A1A1A]/85 text-xs sm:text-sm">
              These terms are governed by applicable local and international commercial standards. For disputes, partnerships, or curator inquiries, contact founder <strong>Pawan Suda</strong> at <a href="mailto:curators@aicorn.design" className="font-bold underline text-[#101010] hover:text-[#FF4B26]">curators@aicorn.design</a>.
            </p>
          </section>

        </div>

      </div>
    </AppLayout>
  );
}
